### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by williamshen-nz** [aidan-curtis/firehose#3]
Might help us debug other stuff

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555ca23 in Cell2Fire::outputGrid (this=0x7fffffffd060) at /usr/include/c++/9/bits/stl_vector.h:1040
1040          operator[](size_type __n) _GLIBCXX_NOEXCEPT
(gdb) bt
#0  0x000055555555ca23 in Cell2Fire::outputGrid (this=0x7fffffffd060) at /usr/include/c++/9/bits/stl_vector.h:1040
#1  0x000055555555e545 in Cell2Fire::Results (this=0x7fffffffd060) at Cell2Fire.cpp:1118
#2  0x0000555555564620 in Cell2Fire::Step (this=0x7fffffffd060, generator=..., rnumber=<optimized out>, rnumber2=<optimized out>, rnumber3=<optimized out>) at Cell2Fire.cpp:1341
#3  0x00005555555676e5 in main._omp_fn.0(void) () at Cell2Fire.cpp:1527
#4  0x00007ffff7c4d8e6 in GOMP_parallel () from /lib/x86_64-linux-gnu/libgomp.so.1
#5  0x000055555555b25a in main (argc=<optimized out>, argv=<optimized out>) at Cell2Fire.cpp:1419
```

At commit https://github.com/aidan-curtis/firehose/commit/433c86c0b9ec222b690e952371b8c7fbbb73b8e9

Set this line to true. Ran, added any input action. On 2nd go will segfault.
https://github.com/aidan-curtis/firehose/blob/main/cell2fire/Cell2FireC/Cell2Fire.cpp#L1509

On Ubuntu. Used gdb: https://stackoverflow.com/questions/3718998/fixing-segmentation-faults-in-c

**Comment by williamshen-nz** [comment]
It doesn't really happen anymore

**Comment by williamshen-nz** [comment]
This isn't an issue anymore, closing
